version: '2'
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    volumes:
     - ./docker/clickhouse/profiling.xml:/etc/clickhouse-server/users.d/profiling.xml
    ports:
     - 9000:9000
#    uncomment when you need not released functionality
    build:
      dockerfile: Docker-master
      context: docker/clickhouse
  clickhouse-flamegraph:
    image: clickhousepro/clickhouse-flamegraph
    volumes:
      - ./:/go/src/github.com/Slach/clickhouse-flamegraph
      - /tmp/:/tmp/
    build:
      context: .
      dockerfile: docker/clickhouse-flamegraph/Dockerfile
    links:
      - clickhouse

 
